SSCS-10146 update sscs-common version
hmcts/sscs-case-loader pull request #1286
Opened 2022-04-05 08:53 UTC by suetlaiHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-10146

### Change description ###
Update sscs-common version for testing the common version hasn’t broke any other services.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-04-20 11:52 UTC, wmarshid approved these changes

2022-04-20 11:58 UTC, MohammedHMCTS requested changes

2022-04-20 11:58 UTC, MohammedHMCTS commented on dependency-check-suppressions.xml
> +    <packageUrl regex="true">^pkg:maven/org\.apache\.xmlgraphics/batik\-i18n@.*$</packageUrl>
Please remove all of this stuff and use the one that is in master

2022-04-21 10:11 UTC, MohammedHMCTS approved these changes

2022-04-22 11:13 UTC, merged